/**
 * Defines the shipping cost per country.
 * Defines shipping information (name and rate) per country.
 * Use ISO 3166-1 alpha-2 country codes (e.g., 'US', 'CA', 'GB') as keys.
 */
interface CountryShippingInfo {
  name: string;
  rate: number;
}

/**
 * The default shipping rate used as a fallback for countries not explicitly listed.
 */
const defaultShippingRate = 15;

const shippingConfig: Record<string, CountryShippingInfo> = {
  // Existing specific rates
  DE: { name: 'Germany', rate: 10 },
  PL: { name: 'Poland', rate: 5 },

  // Countries with default rate
  AF: { name: 'Afghanistan', rate: defaultShippingRate },
  AL: { name: 'Albania', rate: defaultShippingRate },
  DZ: { name: 'Algeria', rate: defaultShippingRate },
  AD: { name: 'Andorra', rate: defaultShippingRate },
  AO: { name: 'Angola', rate: defaultShippingRate },
  AG: { name: 'Antigua and Barbuda', rate: defaultShippingRate },
  AR: { name: 'Argentina', rate: defaultShippingRate },
  AM: { name: 'Armenia', rate: defaultShippingRate },
  AU: { name: 'Australia', rate: defaultShippingRate },
  AT: { name: 'Austria', rate: defaultShippingRate },
  AZ: { name: 'Azerbaijan', rate: defaultShippingRate },
  BS: { name: 'Bahamas', rate: defaultShippingRate },
  BH: { name: 'Bahrain', rate: defaultShippingRate },
  BD: { name: 'Bangladesh', rate: defaultShippingRate },
  BB: { name: 'Barbados', rate: defaultShippingRate },
  BY: { name: 'Belarus', rate: defaultShippingRate },
  BE: { name: 'Belgium', rate: defaultShippingRate },
  BZ: { name: 'Belize', rate: defaultShippingRate },
  BJ: { name: 'Benin', rate: defaultShippingRate },
  BT: { name: 'Bhutan', rate: defaultShippingRate },
  BO: { name: 'Bolivia', rate: defaultShippingRate },
  BA: { name: 'Bosnia and Herzegovina', rate: defaultShippingRate },
  BW: { name: 'Botswana', rate: defaultShippingRate },
  BR: { name: 'Brazil', rate: defaultShippingRate },
  BN: { name: 'Brunei', rate: defaultShippingRate },
  BG: { name: 'Bulgaria', rate: defaultShippingRate },
  BF: { name: 'Burkina Faso', rate: defaultShippingRate },
  BI: { name: 'Burundi', rate: defaultShippingRate },
  CV: { name: 'Cabo Verde', rate: defaultShippingRate },
  KH: { name: 'Cambodia', rate: defaultShippingRate },
  CM: { name: 'Cameroon', rate: defaultShippingRate },
  CA: { name: 'Canada', rate: defaultShippingRate },
  CF: { name: 'Central African Republic', rate: defaultShippingRate },
  TD: { name: 'Chad', rate: defaultShippingRate },
  CL: { name: 'Chile', rate: defaultShippingRate },
  CN: { name: 'China', rate: defaultShippingRate },
  CO: { name: 'Colombia', rate: defaultShippingRate },
  KM: { name: 'Comoros', rate: defaultShippingRate },
  CG: { name: 'Congo', rate: defaultShippingRate },
  CD: { name: 'Congo (DRC)', rate: defaultShippingRate },
  CR: { name: 'Costa Rica', rate: defaultShippingRate },
  CI: { name: 'Côte d\'Ivoire', rate: defaultShippingRate },
  HR: { name: 'Croatia', rate: defaultShippingRate },
  CU: { name: 'Cuba', rate: defaultShippingRate },
  CY: { name: 'Cyprus', rate: defaultShippingRate },
  CZ: { name: 'Czech Republic', rate: defaultShippingRate },
  DK: { name: 'Denmark', rate: defaultShippingRate },
  DJ: { name: 'Djibouti', rate: defaultShippingRate },
  DM: { name: 'Dominica', rate: defaultShippingRate },
  DO: { name: 'Dominican Republic', rate: defaultShippingRate },
  EC: { name: 'Ecuador', rate: defaultShippingRate },
  EG: { name: 'Egypt', rate: defaultShippingRate },
  SV: { name: 'El Salvador', rate: defaultShippingRate },
  GQ: { name: 'Equatorial Guinea', rate: defaultShippingRate },
  ER: { name: 'Eritrea', rate: defaultShippingRate },
  EE: { name: 'Estonia', rate: defaultShippingRate },
  SZ: { name: 'Eswatini', rate: defaultShippingRate },
  ET: { name: 'Ethiopia', rate: defaultShippingRate },
  FJ: { name: 'Fiji', rate: defaultShippingRate },
  FI: { name: 'Finland', rate: defaultShippingRate },
  FR: { name: 'France', rate: defaultShippingRate },
  GA: { name: 'Gabon', rate: defaultShippingRate },
  GM: { name: 'Gambia', rate: defaultShippingRate },
  GE: { name: 'Georgia', rate: defaultShippingRate },
  GH: { name: 'Ghana', rate: defaultShippingRate },
  GR: { name: 'Greece', rate: defaultShippingRate },
  GD: { name: 'Grenada', rate: defaultShippingRate },
  GT: { name: 'Guatemala', rate: defaultShippingRate },
  GN: { name: 'Guinea', rate: defaultShippingRate },
  GW: { name: 'Guinea-Bissau', rate: defaultShippingRate },
  GY: { name: 'Guyana', rate: defaultShippingRate },
  HT: { name: 'Haiti', rate: defaultShippingRate },
  HN: { name: 'Honduras', rate: defaultShippingRate },
  HU: { name: 'Hungary', rate: defaultShippingRate },
  IS: { name: 'Iceland', rate: defaultShippingRate },
  IN: { name: 'India', rate: defaultShippingRate },
  ID: { name: 'Indonesia', rate: defaultShippingRate },
  IR: { name: 'Iran', rate: defaultShippingRate },
  IQ: { name: 'Iraq', rate: defaultShippingRate },
  IE: { name: 'Ireland', rate: defaultShippingRate },
  IL: { name: 'Israel', rate: defaultShippingRate },
  IT: { name: 'Italy', rate: defaultShippingRate },
  JM: { name: 'Jamaica', rate: defaultShippingRate },
  JP: { name: 'Japan', rate: defaultShippingRate },
  JO: { name: 'Jordan', rate: defaultShippingRate },
  KZ: { name: 'Kazakhstan', rate: defaultShippingRate },
  KE: { name: 'Kenya', rate: defaultShippingRate },
  KI: { name: 'Kiribati', rate: defaultShippingRate },
  KP: { name: 'Korea (North)', rate: defaultShippingRate },
  KR: { name: 'Korea (South)', rate: defaultShippingRate },
  KW: { name: 'Kuwait', rate: defaultShippingRate },
  KG: { name: 'Kyrgyzstan', rate: defaultShippingRate },
  LA: { name: 'Laos', rate: defaultShippingRate },
  LV: { name: 'Latvia', rate: defaultShippingRate },
  LB: { name: 'Lebanon', rate: defaultShippingRate },
  LS: { name: 'Lesotho', rate: defaultShippingRate },
  LR: { name: 'Liberia', rate: defaultShippingRate },
  LY: { name: 'Libya', rate: defaultShippingRate },
  LI: { name: 'Liechtenstein', rate: defaultShippingRate },
  LT: { name: 'Lithuania', rate: defaultShippingRate },
  LU: { name: 'Luxembourg', rate: defaultShippingRate },
  MG: { name: 'Madagascar', rate: defaultShippingRate },
  MW: { name: 'Malawi', rate: defaultShippingRate },
  MY: { name: 'Malaysia', rate: defaultShippingRate },
  MV: { name: 'Maldives', rate: defaultShippingRate },
  ML: { name: 'Mali', rate: defaultShippingRate },
  MT: { name: 'Malta', rate: defaultShippingRate },
  MH: { name: 'Marshall Islands', rate: defaultShippingRate },
  MR: { name: 'Mauritania', rate: defaultShippingRate },
  MU: { name: 'Mauritius', rate: defaultShippingRate },
  MX: { name: 'Mexico', rate: defaultShippingRate },
  FM: { name: 'Micronesia', rate: defaultShippingRate },
  MD: { name: 'Moldova', rate: defaultShippingRate },
  MC: { name: 'Monaco', rate: defaultShippingRate },
  MN: { name: 'Mongolia', rate: defaultShippingRate },
  ME: { name: 'Montenegro', rate: defaultShippingRate },
  MA: { name: 'Morocco', rate: defaultShippingRate },
  MZ: { name: 'Mozambique', rate: defaultShippingRate },
  MM: { name: 'Myanmar (Burma)', rate: defaultShippingRate },
  NA: { name: 'Namibia', rate: defaultShippingRate },
  NR: { name: 'Nauru', rate: defaultShippingRate },
  NP: { name: 'Nepal', rate: defaultShippingRate },
  NL: { name: 'Netherlands', rate: defaultShippingRate },
  NZ: { name: 'New Zealand', rate: defaultShippingRate },
  NI: { name: 'Nicaragua', rate: defaultShippingRate },
  NE: { name: 'Niger', rate: defaultShippingRate },
  NG: { name: 'Nigeria', rate: defaultShippingRate },
  MK: { name: 'North Macedonia', rate: defaultShippingRate },
  NO: { name: 'Norway', rate: defaultShippingRate },
  OM: { name: 'Oman', rate: defaultShippingRate },
  PK: { name: 'Pakistan', rate: defaultShippingRate },
  PW: { name: 'Palau', rate: defaultShippingRate },
  PA: { name: 'Panama', rate: defaultShippingRate },
  PG: { name: 'Papua New Guinea', rate: defaultShippingRate },
  PY: { name: 'Paraguay', rate: defaultShippingRate },
  PE: { name: 'Peru', rate: defaultShippingRate },
  PH: { name: 'Philippines', rate: defaultShippingRate },
  PT: { name: 'Portugal', rate: defaultShippingRate },
  QA: { name: 'Qatar', rate: defaultShippingRate },
  RO: { name: 'Romania', rate: defaultShippingRate },
  RU: { name: 'Russia', rate: defaultShippingRate },
  RW: { name: 'Rwanda', rate: defaultShippingRate },
  KN: { name: 'Saint Kitts and Nevis', rate: defaultShippingRate },
  LC: { name: 'Saint Lucia', rate: defaultShippingRate },
  VC: { name: 'Saint Vincent and the Grenadines', rate: defaultShippingRate },
  WS: { name: 'Samoa', rate: defaultShippingRate },
  SM: { name: 'San Marino', rate: defaultShippingRate },
  ST: { name: 'Sao Tome and Principe', rate: defaultShippingRate },
  SA: { name: 'Saudi Arabia', rate: defaultShippingRate },
  SN: { name: 'Senegal', rate: defaultShippingRate },
  RS: { name: 'Serbia', rate: defaultShippingRate },
  SC: { name: 'Seychelles', rate: defaultShippingRate },
  SL: { name: 'Sierra Leone', rate: defaultShippingRate },
  SG: { name: 'Singapore', rate: defaultShippingRate },
  SK: { name: 'Slovakia', rate: defaultShippingRate },
  SI: { name: 'Slovenia', rate: defaultShippingRate },
  SB: { name: 'Solomon Islands', rate: defaultShippingRate },
  SO: { name: 'Somalia', rate: defaultShippingRate },
  ZA: { name: 'South Africa', rate: defaultShippingRate },
  SS: { name: 'South Sudan', rate: defaultShippingRate },
  ES: { name: 'Spain', rate: defaultShippingRate },
  LK: { name: 'Sri Lanka', rate: defaultShippingRate },
  SD: { name: 'Sudan', rate: defaultShippingRate },
  SR: { name: 'Suriname', rate: defaultShippingRate },
  SE: { name: 'Sweden', rate: defaultShippingRate },
  CH: { name: 'Switzerland', rate: defaultShippingRate },
  SY: { name: 'Syria', rate: defaultShippingRate },
  TW: { name: 'Taiwan', rate: defaultShippingRate },
  TJ: { name: 'Tajikistan', rate: defaultShippingRate },
  TZ: { name: 'Tanzania', rate: defaultShippingRate },
  TH: { name: 'Thailand', rate: defaultShippingRate },
  TL: { name: 'Timor-Leste', rate: defaultShippingRate },
  TG: { name: 'Togo', rate: defaultShippingRate },
  TO: { name: 'Tonga', rate: defaultShippingRate },
  TT: { name: 'Trinidad and Tobago', rate: defaultShippingRate },
  TN: { name: 'Tunisia', rate: defaultShippingRate },
  TR: { name: 'Turkey', rate: defaultShippingRate },
  TM: { name: 'Turkmenistan', rate: defaultShippingRate },
  TV: { name: 'Tuvalu', rate: defaultShippingRate },
  UG: { name: 'Uganda', rate: defaultShippingRate },
  UA: { name: 'Ukraine', rate: defaultShippingRate },
  AE: { name: 'United Arab Emirates', rate: defaultShippingRate },
  GB: { name: 'United Kingdom', rate: defaultShippingRate },
  US: { name: 'United States', rate: defaultShippingRate },
  UY: { name: 'Uruguay', rate: defaultShippingRate },
  UZ: { name: 'Uzbekistan', rate: defaultShippingRate },
  VU: { name: 'Vanuatu', rate: defaultShippingRate },
  VA: { name: 'Vatican City', rate: defaultShippingRate },
  VE: { name: 'Venezuela', rate: defaultShippingRate },
  VN: { name: 'Vietnam', rate: defaultShippingRate },
  YE: { name: 'Yemen', rate: defaultShippingRate },
  ZM: { name: 'Zambia', rate: defaultShippingRate },
  ZW: { name: 'Zimbabwe', rate: defaultShippingRate },
  // Add more countries and their info here if needed
};

/**
 * List of explicitly supported country codes for the dropdown, sorted alphabetically.
 */
export const supportedCountries = Object.keys(shippingConfig).sort();

/**
 * Maps supported country codes to their full names for display purposes.
 */
export const countryNames: Record<string, string> = Object.fromEntries(
  Object.entries(shippingConfig).map(([code, info]) => [code, info.name])
);

/**
 * Helper function to get the shipping cost for a given country code.
 * Uses the default rate if the country code is not found in `shippingConfig`.
 * Returns 0 if no countryCode is provided.
 */
export function getShippingCost(countryCode: string | undefined | null): number {
  if (!countryCode) {
    return 0; // No country selected yet
  }
  // Use the rate from the config if the country exists, otherwise use the default rate.
  return shippingConfig[countryCode]?.rate ?? defaultShippingRate;
}
